/**
 * BotScript Compiler - Refactored to align with Flex/Bison patterns (TP1/TP2)
 */

// --- GLOBAL STATE (Mimicking Flex/Bison globals) ---
export let yytext: string = "";
export let yylval: any = null;
export let yylineno: number = 1;
export let yycolumn: number = 1;

export type TokenType =
  | 'ENTIER'
  | 'REEL'
  | 'IDENT'
  | 'MOTCLE'
  | 'OP_ARTHM'
  | 'OP_REL'
  | 'AFFECT'
  | 'PUNCT'
  | 'CHAINE'
  | 'FIN'
  | 'ERROR';

export interface Token {
  type: TokenType;
  value: any;
  line: number;
  col: number;
}

export interface CompilerError {
  type: 'LEXICAL' | 'SYNTACTIC' | 'SEMANTIC';
  message: string;
  line: number;
  col: number;
}

// --- LEXER (Mimicking Flex yylex) ---
export class Lexer {
  private pos = 0;
  private tokens: Token[] = [];
  public errors: CompilerError[] = [];

  constructor(private input: string) {
    yylineno = 1;
    yycolumn = 1;
  }

  // Equivalent to the yylex() function generated by Flex
  public yylex(): Token {
    while (this.pos < this.input.length) {
      const char = this.input[this.pos];

      // Ignorer les espaces, tabulations, passages à la ligne (TP1 Ex 5a)
      if (/\s/.test(char)) {
        if (char === '\n') {
          yylineno++;
          yycolumn = 1;
        } else {
          yycolumn++;
        }
        this.pos++;
        continue;
      }

      // COMMENTAIRE : une ligne commençant par # or // (TP1 Ex 5)
      if ((char === '#' ) || (char === '/' && this.input[this.pos + 1] === '/')) {
        const startPos = this.pos;
        while (this.pos < this.input.length && this.input[this.pos] !== '\n') {
          this.pos++;
          yycolumn++;
        }
        // Action: ignore comment
        continue;
      }

      // REEL et ENTIER (TP1 Ex 5)
      if (/[0-9]/.test(char)) {
        let valueStr = "";
        const startCol = yycolumn;
        let isReal = false;
        
        while (this.pos < this.input.length && /[0-9.]/.test(this.input[this.pos])) {
          if (this.input[this.pos] === '.') isReal = true;
          valueStr += this.input[this.pos];
          this.pos++;
          yycolumn++;
        }
        
        yytext = valueStr;
        yylval = isReal ? parseFloat(valueStr) : parseInt(valueStr);
        return { type: isReal ? 'REEL' : 'ENTIER', value: yylval, line: yylineno, col: startCol };
      }

      // IDENT et MOTCLE (TP1 Ex 5)
      if (/[a-zA-Z_]/.test(char)) {
        let valueStr = "";
        const startCol = yycolumn;
        while (this.pos < this.input.length && /[a-zA-Z0-9_]/.test(this.input[this.pos])) {
          valueStr += this.input[this.pos];
          this.pos++;
          yycolumn++;
        }
        
        yytext = valueStr;
        const keywords = ['let', 'repeat', 'if', 'else', 'while', 'forward', 'turn', 'color', 'penDown', 'penUp'];
        if (keywords.includes(valueStr)) {
          return { type: 'MOTCLE', value: valueStr, line: yylineno, col: startCol };
        } else {
          return { type: 'IDENT', value: valueStr, line: yylineno, col: startCol };
        }
      }

      // CHAINE (TP1 Ex 5)
      if (char === '"' || char === "'") {
        const quote = char;
        let valueStr = "";
        const startCol = yycolumn;
        this.pos++; yycolumn++;
        while (this.pos < this.input.length && this.input[this.pos] !== quote) {
          valueStr += this.input[this.pos];
          this.pos++; yycolumn++;
        }
        if (this.pos < this.input.length) {
          this.pos++; yycolumn++;
        } else {
          this.yyerror(`Chaîne incomplète`, yylineno, startCol, 'LEXICAL');
        }
        yytext = valueStr;
        return { type: 'CHAINE', value: valueStr, line: yylineno, col: startCol };
      }

      // OP_REL (TP1 Ex 5)
      if ('<>=!'.includes(char)) {
        let op = char;
        const startCol = yycolumn;
        this.pos++; yycolumn++;
        if (this.pos < this.input.length && this.input[this.pos] === '=') {
          op += '=';
          this.pos++; yycolumn++;
        }
        yytext = op;
        if (op === '=') return { type: 'AFFECT', value: op, line: yylineno, col: startCol };
        return { type: 'OP_REL', value: op, line: yylineno, col: startCol };
      }

      // OP_ARTHM (TP1 Ex 5)
      if ('+-*/'.includes(char)) {
        yytext = char;
        const startCol = yycolumn;
        this.pos++; yycolumn++;
        return { type: 'OP_ARTHM', value: char, line: yylineno, col: startCol };
      }

      // PUNCT
      if ('(){};,'.includes(char)) {
        yytext = char;
        const startCol = yycolumn;
        this.pos++; yycolumn++;
        return { type: 'PUNCT', value: char, line: yylineno, col: startCol };
      }

      // Erreur Lexicale
      this.yyerror(`Caractère inattendu: '${char}'`, yylineno, yycolumn, 'LEXICAL');
      this.pos++; yycolumn++;
    }

    return { type: 'FIN', value: '', line: yylineno, col: yycolumn };
  }

  private yyerror(msg: string, line: number, col: number, type: 'LEXICAL' | 'SYNTACTIC' | 'SEMANTIC' = 'SYNTACTIC') {
    this.errors.push({ type, message: msg, line, col });
  }
}

// --- PARSER (Mimicking Bison yyparse) ---

export type ASTNode =
  | { type: 'Program'; body: ASTNode[] }
  | { type: 'VarDecl'; name: string; value: ASTNode }
  | { type: 'Assignment'; name: string; value: ASTNode }
  | { type: 'Repeat'; count: ASTNode; body: ASTNode[] }
  | { type: 'If'; condition: ASTNode; thenBody: ASTNode[]; elseBody?: ASTNode[] }
  | { type: 'While'; condition: ASTNode; body: ASTNode[] }
  | { type: 'Command'; name: string; args: ASTNode[] }
  | { type: 'BinaryExpr'; left: ASTNode; operator: string; right: ASTNode }
  | { type: 'Literal'; value: any }
  | { type: 'Identifier'; name: string };

export class Parser {
  private currentToken: Token;
  public errors: CompilerError[] = [];

  constructor(private lexer: Lexer) {
    this.currentToken = this.lexer.yylex();
  }

  // Equivalent to the yyparse() function generated by Bison
  public yyparse(): { ast: ASTNode; errors: CompilerError[] } {
    const body: ASTNode[] = [];
    while (this.currentToken.type !== 'FIN') {
      try {
        body.push(this.parseStatement());
      } catch (e) {
        // Error recovery
        while ((this.currentToken.type as any) !== 'FIN' && 
               this.currentToken.value !== ';' && 
               this.currentToken.value !== '}') {
          this.advance();
        }
        if (this.currentToken.value === ';' || this.currentToken.value === '}') this.advance();
      }
    }
    return { ast: { type: 'Program', body }, errors: this.errors };
  }

  private parseStatement(): ASTNode {
    const t = this.currentToken;
    
    // MOTCLE rules
    if (t.type === 'MOTCLE') {
      if (t.value === 'let') return this.parseVarDecl();
      if (t.value === 'repeat') return this.parseRepeat();
      if (t.value === 'if') return this.parseIf();
      if (t.value === 'while') return this.parseWhile();
      // Commands are also keywords in this simplified DSL
      return this.parseCommand();
    }

    // IDENT rules
    if (t.type === 'IDENT') {
      return this.parseAssignment();
    }

    throw this.yyerror(`Token inattendu: ${t.value}`);
  }

  private parseVarDecl(): ASTNode {
    this.consume('MOTCLE', 'let');
    const name = this.consume('IDENT').value;
    this.consume('AFFECT', '=');
    const value = this.parseExpression();
    this.consume('PUNCT', ';');
    return { type: 'VarDecl', name, value };
  }

  private parseAssignment(): ASTNode {
    const name = this.consume('IDENT').value;
    this.consume('AFFECT', '=');
    const value = this.parseExpression();
    this.consume('PUNCT', ';');
    return { type: 'Assignment', name, value };
  }

  private parseRepeat(): ASTNode {
    this.consume('MOTCLE', 'repeat');
    const count = this.parseExpression();
    this.consume('PUNCT', '{');
    const body: ASTNode[] = [];
    while (this.currentToken.value !== '}' && this.currentToken.type !== 'FIN') {
      body.push(this.parseStatement());
    }
    this.consume('PUNCT', '}');
    return { type: 'Repeat', count, body };
  }

  private parseIf(): ASTNode {
    this.consume('MOTCLE', 'if');
    this.consume('PUNCT', '(');
    const condition = this.parseExpression();
    this.consume('PUNCT', ')');
    this.consume('PUNCT', '{');
    const thenBody: ASTNode[] = [];
    while (this.currentToken.value !== '}' && this.currentToken.type !== 'FIN') {
      thenBody.push(this.parseStatement());
    }
    this.consume('PUNCT', '}');

    let elseBody: ASTNode[] | undefined;
    if (this.currentToken.value === 'else') {
      this.advance();
      this.consume('PUNCT', '{');
      elseBody = [];
      while (this.currentToken.value !== '}' && this.currentToken.type !== 'FIN') {
        elseBody.push(this.parseStatement());
      }
      this.consume('PUNCT', '}');
    }

    return { type: 'If', condition, thenBody, elseBody };
  }

  private parseWhile(): ASTNode {
    this.consume('MOTCLE', 'while');
    this.consume('PUNCT', '(');
    const condition = this.parseExpression();
    this.consume('PUNCT', ')');
    this.consume('PUNCT', '{');
    const body: ASTNode[] = [];
    while (this.currentToken.value !== '}' && this.currentToken.type !== 'FIN') {
      body.push(this.parseStatement());
    }
    this.consume('PUNCT', '}');
    return { type: 'While', condition, body };
  }

  private parseCommand(): ASTNode {
    const name = this.consume('MOTCLE').value;
    this.consume('PUNCT', '(');
    const args: ASTNode[] = [];
    if (this.currentToken.value !== ')') {
      args.push(this.parseExpression());
      while (this.currentToken.value === ',') {
        this.advance();
        args.push(this.parseExpression());
      }
    }
    this.consume('PUNCT', ')');
    this.consume('PUNCT', ';');
    return { type: 'Command', name, args };
  }

  private parseExpression(): ASTNode {
    return this.parseBinaryExpr(0);
  }

  private parseBinaryExpr(precedence: number): ASTNode {
    let left = this.parsePrimary();

    const opPrecedence: Record<string, number> = {
      '+': 1, '-': 1, '*': 2, '/': 2,
      '==': 0, '!=': 0, '<': 0, '>': 0, '<=': 0, '>=': 0
    };

    while (true) {
      const op = this.currentToken.value;
      const prec = opPrecedence[op];
      if (prec === undefined || prec <= precedence) break;

      this.advance();
      const right = this.parseBinaryExpr(prec);
      left = { type: 'BinaryExpr', left, operator: op, right };
    }

    return left;
  }

  private parsePrimary(): ASTNode {
    const t = this.currentToken;
    if (t.type === 'ENTIER' || t.type === 'REEL' || t.type === 'CHAINE') {
      this.advance();
      return { type: 'Literal', value: t.value };
    }
    if (t.type === 'IDENT') {
      this.advance();
      return { type: 'Identifier', name: t.value };
    }
    if (t.value === '(') {
      this.advance();
      const expr = this.parseExpression();
      this.consume('PUNCT', ')');
      return expr;
    }
    throw this.yyerror(`Expression attendue, reçu ${t.value}`);
  }

  private advance(): Token {
    const old = this.currentToken;
    this.currentToken = this.lexer.yylex();
    return old;
  }

  private consume(type: TokenType, value?: string): Token {
    const t = this.currentToken;
    if (t.type !== type || (value && t.value !== value)) {
      throw this.yyerror(`Attendu ${value || type}, reçu ${t.value}`);
    }
    return this.advance();
  }

  private yyerror(message: string, line?: number, col?: number, type: 'LEXICAL' | 'SYNTACTIC' | 'SEMANTIC' = 'SYNTACTIC'): Error {
    const err: CompilerError = { 
      type, 
      message, 
      line: line || this.currentToken.line, 
      col: col || this.currentToken.col 
    };
    this.errors.push(err);
    return new Error(message);
  }
}

// --- INTERPRETER (Semantic Actions) ---

export interface RobotState {
  x: number;
  y: number;
  angle: number;
  penDown: boolean;
  color: string;
  history: { x: number; y: number; penDown: boolean; color: string }[];
}

export class Interpreter {
  private variables: Map<string, any> = new Map();
  private state: RobotState = {
    x: 250,
    y: 250,
    angle: 0,
    penDown: true,
    color: '#3b82f6',
    history: [{ x: 250, y: 250, penDown: true, color: '#3b82f6' }],
  };
  public errors: CompilerError[] = [];

  constructor(private ast: ASTNode) {}

  public execute(): { state: RobotState; errors: CompilerError[] } {
    try {
      this.visit(this.ast);
    } catch (e: any) {
      this.errors.push({
        type: 'SEMANTIC',
        message: e.message,
        line: 0,
        col: 0,
      });
    }
    return { state: this.state, errors: this.errors };
  }

  private visit(node: ASTNode): any {
    if (!node) return null;
    switch (node.type) {
      case 'Program':
        for (const stmt of node.body) this.visit(stmt);
        break;
      case 'VarDecl':
        this.variables.set(node.name, this.visit(node.value));
        break;
      case 'Assignment':
        if (!this.variables.has(node.name)) {
          throw new Error(`Variable non définie: ${node.name}`);
        }
        this.variables.set(node.name, this.visit(node.value));
        break;
      case 'Repeat':
        const count = this.visit(node.count);
        for (let i = 0; i < count; i++) {
          for (const stmt of node.body) this.visit(stmt);
        }
        break;
      case 'If':
        if (this.visit(node.condition)) {
          for (const stmt of node.thenBody) this.visit(stmt);
        } else if (node.elseBody) {
          for (const stmt of node.elseBody) this.visit(stmt);
        }
        break;
      case 'While':
        while (this.visit(node.condition)) {
          for (const stmt of node.body) this.visit(stmt);
        }
        break;
      case 'Command':
        this.executeCommand(node.name, node.args.map(a => this.visit(a)));
        break;
      case 'BinaryExpr':
        const left = this.visit(node.left);
        const right = this.visit(node.right);
        switch (node.operator) {
          case '+': return left + right;
          case '-': return left - right;
          case '*': return left * right;
          case '/': return left / right;
          case '==': return left == right;
          case '!=': return left != right;
          case '<': return left < right;
          case '>': return left > right;
          case '<=': return left <= right;
          case '>=': return left >= right;
        }
        break;
      case 'Literal':
        return node.value;
      case 'Identifier':
        if (!this.variables.has(node.name)) {
          throw new Error(`Variable non définie: ${node.name}`);
        }
        return this.variables.get(node.name);
    }
  }

  private executeCommand(name: string, args: any[]) {
    switch (name) {
      case 'forward':
        const dist = args[0];
        const rad = (this.state.angle * Math.PI) / 180;
        this.state.x += Math.cos(rad) * dist;
        this.state.y += Math.sin(rad) * dist;
        this.state.history.push({
          x: this.state.x,
          y: this.state.y,
          penDown: this.state.penDown,
          color: this.state.color,
        });
        break;
      case 'turn':
        this.state.angle += args[0];
        break;
      case 'color':
        this.state.color = args[0];
        break;
      case 'penDown':
        this.state.penDown = true;
        break;
      case 'penUp':
        this.state.penDown = false;
        break;
      default:
        throw new Error(`Commande inconnue: ${name}`);
    }
  }
}
